# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3b4209803efcf03fbcce73f3ea687fa7db5f8815c557de6849b1df118437eaac6752866575bba31e17a7fd722eeb3efdf3c4d9dcd5fe118c2dac35fb0a6bc3c

test:
  secret_key_base: 8bc419c763cca0adf69c81921add9269e54aac6b4e57d2b6707dc9bf4e0d4d24574c5a68402b00f345681cc159998f09ac91f4ef26983396ecf87f33d029783d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
